modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="AGPL-3.0"

[[mods]] #mandatory

modId="nightvision" #mandatory
version="0.0.3" #mandatory

displayName="Night Vision Enchantment" #mandatory

logoFile="NightVisLogo.png" #optional

authors="Shutdoor" #optional

description="Adds a Night Vision Enchantment for helmets into the game."

[[dependencies.nightvision]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.nightvision]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
