modLoader="javafml" #mandatory

loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="AGPL-3.0"

[[mods]] #mandatory

modId="nightvision" #mandatory
version="1.19.4-0.0.1" #mandatory

displayName="Night Vision Enchantment" #mandatory

logoFile="NightVisLogo.png" #optional

authors="Shutdoor" #optional

description="Adds a Night Vision Enchantment for helmets into the game."

[[dependencies.nightvision]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[45,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.nightvision]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"